import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const ALLOWED_ORIGINS=new Set(['https://donaantonia.com.br','https://www.donaantonia.com.br']);
const BASE_CORS={"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const cors=(req:Request)=>{const origin=req.headers.get('origin');if(origin&& !ALLOWED_ORIGINS.has(origin))return null;return {...BASE_CORS,"Access-Control-Allow-Origin":origin||'https://donaantonia.com.br',"Vary":"Origin"}};
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...(cors(req)||BASE_CORS),"Content-Type":"application/json","Cache-Control":"no-store"}});
const clean=(v:unknown,max=500)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max);
const digits=(v:unknown)=>String(v??"").replace(/\D/g,"");
const qty=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(999,n)):null};
const validToken=(v:unknown)=>/^[a-f0-9]{64}$/i.test(clean(v,80));
const validUuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(clean(v,80));
const normalize=(v:unknown)=>clean(v,400).toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const groups=[{id:'baskets',label:'Cestas Básicas',icon:'🧺'},{id:'mercearia',label:'Mercearia Completa',icon:'🛒'},{id:'limpeza_lavanderia',label:'Limpeza e Lavanderia',icon:'🧼'},{id:'higiene_beleza',label:'Higiene e Beleza',icon:'🧴'},{id:'casa_pet',label:'Casa e Pet',icon:'🏠'}];
const MIME={audio:new Set(['audio/webm','audio/ogg','audio/mpeg','audio/mp4','audio/aac']),image:new Set(['image/jpeg','image/png','image/webp','image/heic','image/heif'])};
const EXT:Record<string,string>={'audio/webm':'webm','audio/ogg':'ogg','audio/mpeg':'mp3','audio/mp4':'m4a','audio/aac':'aac','image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/heic':'heic','image/heif':'heif'};
const PASSIVE_SALES_EVENTS=new Set(['viewed','added','rejected','ignored','accepted_category']);
function intentFor(input:string){const s=normalize(input);if(/\b(nao quero|não quero|so a cesta|só a cesta|somente a cesta|sem mais nada)\b/.test(s))return {type:'decline_upsell'};if(/\b(pressa|rapido|rápido|correndo|finaliza logo)\b/.test(s))return {type:'fast_checkout'};if(/\b(finalizar|fechar|concluir|terminar|confirmar pedido)\b/.test(s))return {type:'checkout'};if(/\b(oferta|ofertas|promocao|promoção|barato|baratos)\b/.test(s))return {type:'offers'};if(/\b(cesta|cestas)\b/.test(s))return {type:'baskets'};if(/\b(limpeza|lavanderia|sabao|sabão|amaciante|desinfetante)\b/.test(s))return {type:'category',category:'limpeza_lavanderia'};if(/\b(higiene|beleza|creme|shampoo|sabonete|desodorante|nivea|nívea)\b/.test(s))return {type:'category',category:'higiene_beleza'};if(/\b(pet|pets|cachorro|gato|casa|vassoura|rodo|balde)\b/.test(s))return {type:'category',category:'casa_pet'};if(/\b(mercearia|arroz|feijao|feijão|cafe|café|molho|tempero|macarrao|macarrão)\b/.test(s))return {type:'category',category:'mercearia'};return {type:'search',q:clean(input,120)}}
async function sha256(input:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(input));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function rateKey(req:Request,suffix=''){const ip=(req.headers.get('x-forwarded-for')||req.headers.get('cf-connecting-ip')||'unknown').split(',')[0].trim();const ua=req.headers.get('user-agent')||'';return sha256(`${ip}|${ua}|${suffix}`)}
Deno.serve(async(req:Request)=>{
  const ch=cors(req);if(!ch)return new Response('forbidden',{status:403});if(req.method==='OPTIONS')return new Response('ok',{headers:ch});if(req.method!=='POST')return json(req,{ok:false,error:'method_not_allowed'},405);
  const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json(req,{ok:false,error:'server_config'},500);const sb=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
  const ct=req.headers.get('content-type')||'';let body:any={},form:FormData|null=null,file:File|null=null;if(ct.includes('multipart/form-data')){try{form=await req.formData();body={action:form.get('action'),token:form.get('token'),kind:form.get('kind'),duration_ms:form.get('duration_ms')};const f=form.get('file');if(f instanceof File)file=f}catch{return json(req,{ok:false,error:'invalid_form'},400)}}else{try{body=await req.json()}catch{return json(req,{ok:false,error:'invalid_json'},400)}}const action=clean(body?.action||'open',60).toLowerCase();
  if(action==='create_web_room'){const rk=await rateKey(req,'create_room');const {data:allowed}=await sb.rpc('consume_public_rate_limit',{p_rate_key:rk,p_bucket:'create_room',p_limit:20,p_window_seconds:3600});if(!allowed)return json(req,{ok:false,error:'rate_limited'},429);const {data,error}=await sb.rpc('room_start_web_session');if(error)return json(req,{ok:false,error:'room_create_failed',detail:error.message},400);return json(req,{ok:true,...data,room_url:`https://donaantonia.com.br/comprar/?s=${data.token}`})}
  const token=clean(body?.token,80);if(!validToken(token))return json(req,{ok:false,error:'invalid_token'},400);const {data:session,error:se}=await sb.from('catalog_sessions').select('id,public_token,customer_id,conversation_id,cart_id,kind,title,status,expires_at,last_opened_at,last_activity_at,current_view,completed_at,metadata').eq('public_token',token).maybeSingle();if(se)return json(req,{ok:false,error:'room_lookup_failed'},500);if(!session)return json(req,{ok:false,error:'room_not_found'},404);const expired=new Date(session.expires_at).getTime()<=Date.now();if(expired&&session.status!=='closed')return json(req,{ok:false,error:'room_expired'},410);if(session.status==='closed'&&action!=='open'&&action!=='return_whatsapp')return json(req,{ok:false,error:'room_closed'},409);
  const whatsappUrl=async(message='Quero continuar meu pedido.')=>{let phone='556584491018';if(session.conversation_id){const {data:conv}=await sb.from('conversations').select('whatsapp_account:whatsapp_accounts(phone_e164)').eq('id',session.conversation_id).maybeSingle();const found=digits((conv as any)?.whatsapp_account?.phone_e164);if(found)phone=found}return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`};
  const cartSnapshot=async()=>{const {data:s}=await sb.from('catalog_sessions').select('cart_id').eq('id',session.id).single();if(!s?.cart_id)return null;const {data:c}=await sb.from('carts').select('id,status,total,fiscal_subtotal,other_expenses,discount,version,basket_id').eq('id',s.cart_id).maybeSingle();if(!c)return null;const {data:items}=await sb.from('cart_items').select('product_id,source,quantity,base_quantity,commercial_delta,metadata,product:products(id,name,price,image_url,stock)').eq('cart_id',c.id).gt('quantity',0).order('created_at');return {...c,items:items||[]}};
  if(action==='open'){
    if(session.status==='closed'){const {data:o}=session.cart_id?await sb.from('orders').select('id,status,total,bling_order_id,created_at').eq('cart_id',session.cart_id).order('created_at',{ascending:false}).limit(1).maybeSingle():{data:null} as any;return json(req,{ok:true,closed:true,session:{title:session.title,current_view:'success',completed_at:session.completed_at},order:o||null,whatsapp_url:await whatsappUrl('Quero falar sobre meu pedido.')})}
    const firstOpen=!session.last_opened_at||(Date.now()-new Date(session.last_opened_at).getTime())>30*60*1000;await sb.from('catalog_sessions').update({last_opened_at:new Date().toISOString(),last_activity_at:new Date().toISOString(),experience:'shopping_room'}).eq('id',session.id);if(session.conversation_id)await sb.from('conversations').update({room_last_active_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',session.conversation_id);if(firstOpen)await sb.from('catalog_events').insert({catalog_session_id:session.id,customer_id:session.customer_id,event_type:'catalog_open',event_data:{source:'shopping_room'}});
    let customer:any=null;if(session.customer_id){const {data:c}=await sb.from('customers').select('id,name,preferred_reply,shopping_mode,catalog_skill_score,bling_contact_id,cpf_cnpj,primary_whatsapp_e164').eq('id',session.customer_id).maybeSingle();customer=c||null}
    let messages:any[]=[];if(session.conversation_id){const {data:m}=await sb.from('messages').select('id,direction,message_type,body_text,transcript,created_at').eq('conversation_id',session.conversation_id).in('message_type',['text','audio','image','system']).order('created_at',{ascending:false}).limit(20);messages=(m||[]).reverse();const mids=messages.filter((x:any)=>x.message_type==='audio'||x.message_type==='image').map((x:any)=>x.id);if(mids.length){const {data:media}=await sb.from('room_media').select('message_id,kind,object_path,mime_type,duration_ms').in('message_id',mids);const by=new Map<string,any>();for(const r of media||[]){const {data:signed}=await sb.storage.from('shopping-room-media').createSignedUrl(r.object_path,3600);by.set(r.message_id,{...r,media_url:signed?.signedUrl||null})}messages=messages.map((x:any)=>({...x,...(by.get(x.id)||{})}))}}
    const {data:recommended}=await sb.from('catalog_session_items').select('product_id,rank,reason,quantity,product:products(id,name,price,image_url,category,sales_category,brand,packaging,stock,is_offer)').eq('catalog_session_id',session.id).order('rank').limit(12);const {data:baskets}=await sb.from('basket_templates').select('id,name,description,image_url,base_price,sort_order').eq('is_active',true).eq('is_whatsapp_active',true).order('sort_order').limit(8);
    return json(req,{ok:true,session:{title:session.title,kind:session.kind,current_view:session.current_view,expires_at:session.expires_at},customer:customer?{id:customer.id,name:customer.name,phone:customer.primary_whatsapp_e164,preferred_reply:customer.preferred_reply,shopping_mode:customer.shopping_mode,has_bling_contact:!!customer.bling_contact_id,has_document:!!digits(customer.cpf_cnpj)}:null,groups,baskets:baskets||[],recommended:recommended||[],cart:await cartSnapshot(),messages,whatsapp_url:await whatsappUrl('Quero continuar meu pedido pelo WhatsApp.')});
  }
  if(action==='messages'){
    const rk=await rateKey(req,session.id);const {data:allowed}=await sb.rpc('consume_public_rate_limit',{p_rate_key:rk,p_bucket:'room_messages',p_limit:360,p_window_seconds:3600});if(!allowed)return json(req,{ok:false,error:'rate_limited'},429);
    const {data:rows,error}=await sb.from('messages').select('id,direction,message_type,body_text,transcript,ai_interpretation,created_at').eq('conversation_id',session.conversation_id).in('message_type',['text','audio','image','system']).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(30);if(error)return json(req,{ok:false,error:'messages_failed'},500);
    const messages=(rows||[]).reverse();const ids=messages.map((m:any)=>m.id);const {data:media,error:mediaError}=ids.length?await sb.from('room_media').select('message_id,kind,object_path,mime_type,duration_ms,processing_status').eq('conversation_id',session.conversation_id).in('message_id',ids).order('message_id'):{data:[],error:null};if(mediaError)return json(req,{ok:false,error:'messages_failed'},500);
    const by=new Map((media||[]).map((m:any)=>[m.message_id,m]));const cursor=await sha256(JSON.stringify({messages,media}));const pending=(media||[]).some((m:any)=>['uploaded','queued'].includes(m.processing_status));if(body?.cursor===cursor)return json(req,{ok:true,unchanged:true,cursor,pending});const result=[];for(const m of messages){const r:any=by.get(m.id);let media_url=null;if(r){const {data:signed}=await sb.storage.from('shopping-room-media').createSignedUrl(r.object_path,3600);media_url=signed?.signedUrl||null;}result.push({id:m.id,direction:m.direction,message_type:m.message_type,body_text:m.body_text,transcript:m.transcript,created_at:m.created_at,ui:m.ai_interpretation?.ui||null,processing_status:r?.processing_status||null,media_url,duration_ms:r?.duration_ms||null});}return json(req,{ok:true,messages:result,cursor,pending});
  }
  if(action==='preferences'){const {data,error}=await sb.rpc('room_save_customer_preferences',{p_public_token:token,p_day:body?.birthday_day??null,p_month:body?.birthday_month??null,p_marketing_opt_in:typeof body?.marketing_opt_in==='boolean'?body.marketing_opt_in:null});if(error)return json(req,{ok:false,error:'preferences_failed',detail:error.message},400);return json(req,{ok:true,preferences:data});}
  if(action==='sales_move_preview'){
    const rk=await rateKey(req,session.id);const {data:allowed}=await sb.rpc('consume_public_rate_limit',{p_rate_key:rk,p_bucket:'room_sales_preview',p_limit:120,p_window_seconds:3600});if(!allowed)return json(req,{ok:false,error:'rate_limited'},429);
    const {data:plan,error}=await sb.rpc('plan_next_sales_move',{p_conversation_id:session.conversation_id});if(error)return json(req,{ok:false,error:'sales_plan_failed'},500);
    return json(req,{ok:true,plan});
  }
  if(action==='sales_event'){
    const eventType=clean(body?.event_type,40);if(!PASSIVE_SALES_EVENTS.has(eventType))return json(req,{ok:false,error:'invalid_sales_event'},400);
    const productId=body?.product_id==null?null:clean(body.product_id,80);if(productId&&!validUuid(productId))return json(req,{ok:false,error:'invalid_product'},400);
    const context=body?.context&&typeof body.context==='object'?body.context:{};const safeContext={surface:clean(context.surface||'shopping_room',40),slot:clean(context.slot||'',40),reason:clean(context.reason||'',200)};
    const {data:event,error}=await sb.rpc('record_sales_offer_event',{p_conversation_id:session.conversation_id,p_event_type:eventType,p_product_id:productId,p_source:'shopping_room',p_context:safeContext});if(error)return json(req,{ok:false,error:'sales_event_failed'},500);
    return json(req,{ok:true,event});
  }
  if(action==='upload_media'){
    if(!file)return json(req,{ok:false,error:'file_required'},400);const kind=clean(body?.kind,20);if(kind!=='audio'&&kind!=='image')return json(req,{ok:false,error:'invalid_media_kind'},400);const mime=file.type.split(';')[0].trim().toLowerCase();if(!MIME[kind as 'audio'|'image'].has(mime))return json(req,{ok:false,error:'unsupported_media_type'},415);if(file.size<=0||file.size>10485760)return json(req,{ok:false,error:'media_too_large'},413);
    const rk=await rateKey(req,session.id);const {data:allowed}=await sb.rpc('consume_public_rate_limit',{p_rate_key:rk,p_bucket:'room_media',p_limit:60,p_window_seconds:3600});if(!allowed)return json(req,{ok:false,error:'rate_limited'},429);
    const ext=EXT[mime]||'bin',path=`sessions/${session.id}/${kind}/${new Date().toISOString().slice(0,7)}/${crypto.randomUUID()}.${ext}`;const {error:up}=await sb.storage.from('shopping-room-media').upload(path,file,{contentType:mime,upsert:false});if(up)return json(req,{ok:false,error:'media_upload_failed',detail:up.message},400);
    const {data:msg,error:me}=await sb.from('messages').insert({conversation_id:session.conversation_id,direction:'inbound',message_type:kind,body_text:null,media_id:path,raw_event:{source:'shopping_room',session_id:session.id,mime_type:mime,size:file.size}}).select('id,direction,message_type,created_at').single();if(me){await sb.storage.from('shopping-room-media').remove([path]);return json(req,{ok:false,error:'media_message_failed'},400)}
    const duration=Math.max(0,Math.min(Number(body?.duration_ms)||0,10*60*1000))||null;const {data:rm,error:re}=await sb.from('room_media').insert({catalog_session_id:session.id,conversation_id:session.conversation_id,customer_id:session.customer_id,message_id:msg.id,kind,bucket:'shopping-room-media',object_path:path,mime_type:mime,bytes:file.size,duration_ms:duration,processing_status:'uploaded'}).select('id').single();if(re)return json(req,{ok:false,error:'media_record_failed'},400);
    const jobType=kind==='audio'?'transcription':'vision';const {data:job}=await sb.rpc('queue_ai_job_for_message',{p_message_id:msg.id,p_job_type:jobType,p_input:{room_media_id:rm.id,object_path:path,mime_type:mime}});await sb.from('room_media').update({processing_status:job?.status==='pending'?'queued':'held'}).eq('id',rm.id);await sb.from('catalog_sessions').update({last_activity_at:new Date().toISOString()}).eq('id',session.id);const {data:signed}=await sb.storage.from('shopping-room-media').createSignedUrl(path,3600);return json(req,{ok:true,message:{...msg,media_url:signed?.signedUrl||null,duration_ms:duration,processing_status:job?.status==='pending'?'queued':'held'},ai_job:job||null});
  }
  if(action==='identify'){const {data,error}=await sb.rpc('room_identify_customer',{p_public_token:token,p_name:clean(body?.name,120),p_phone:clean(body?.phone,40),p_document:clean(body?.document,30)||null});if(error)return json(req,{ok:false,error:'identify_failed',detail:error.message},400);return json(req,{ok:true,customer:data})}
  if(action==='save_address'){const address=body?.delivery_address&&typeof body.delivery_address==='object'?body.delivery_address:{};const {data,error}=await sb.rpc('room_save_address',{p_public_token:token,p_address:address});if(error)return json(req,{ok:false,error:'address_failed',detail:error.message},400);return json(req,{ok:true,address:data})}
  if(action==='products'){const q=clean(body?.q,100).replace(/[,%()]/g,' ').trim(),category=clean(body?.category,40),offers=body?.offers===true,limit=Math.max(1,Math.min(Number(body?.limit)||24,40));let query=sb.from('products').select('id,name,price,image_url,brand,packaging,category,sales_category,stock,is_offer,sort_order').eq('physically_verified',true).eq('is_active',true).eq('is_whatsapp_active',true).gt('stock',0).order('sort_order').order('name').limit(limit);if(category&&['mercearia','limpeza_lavanderia','higiene_beleza','casa_pet'].includes(category))query=query.eq('sales_category',category);if(offers)query=query.eq('is_offer',true);if(q)query=query.or(`name.ilike.%${q}%,brand.ilike.%${q}%,category.ilike.%${q}%,packaging.ilike.%${q}%`);const {data,error}=await query;if(error)return json(req,{ok:false,error:'products_failed',detail:error.message},400);const ids=(data||[]).map((p:any)=>p.id);let selected:any[]=[];const current=await cartSnapshot();if(current&&ids.length)selected=(current.items||[]).filter((x:any)=>ids.includes(x.product_id));const map=new Map(selected.map((x:any)=>[x.product_id,Number(x.quantity||0)]));return json(req,{ok:true,products:(data||[]).map((p:any)=>({...p,quantity:map.get(p.id)||0}))})}
  if(action==='baskets'){const {data,error}=await sb.from('basket_templates').select('id,name,description,image_url,base_price,sort_order').eq('is_active',true).eq('is_whatsapp_active',true).order('sort_order').order('name').limit(30);if(error)return json(req,{ok:false,error:'baskets_failed'},400);return json(req,{ok:true,baskets:data||[]})}
  if(action==='start_basket'){const id=clean(body?.basket_id,80);if(!validUuid(id))return json(req,{ok:false,error:'invalid_basket'},400);const {data,error}=await sb.rpc('room_start_basket',{p_public_token:token,p_basket_id:id});if(error)return json(req,{ok:false,error:'basket_start_failed',detail:error.message},400);const {data:items}=await sb.from('cart_items').select('product_id,source,quantity,base_quantity,commercial_delta,metadata,product:products(id,name,image_url,stock)').eq('cart_id',data.cart_id).order('created_at');return json(req,{ok:true,result:data,items:items||[],cart:await cartSnapshot()})}
  if(action==='set_quantity'){const id=clean(body?.product_id,80),quantity=qty(body?.quantity);if(!validUuid(id)||quantity===null)return json(req,{ok:false,error:'invalid_quantity'},400);const {data,error}=await sb.rpc('room_set_product_quantity',{p_public_token:token,p_product_id:id,p_quantity:quantity});if(error)return json(req,{ok:false,error:'quantity_failed',detail:error.message},400);return json(req,{ok:true,...data})}
  if(action==='set_basket_quantity'){const id=clean(body?.product_id,80),quantity=qty(body?.quantity);if(!validUuid(id)||quantity===null)return json(req,{ok:false,error:'invalid_quantity'},400);const {data,error}=await sb.rpc('room_set_basket_quantity',{p_public_token:token,p_product_id:id,p_quantity:quantity});if(error)return json(req,{ok:false,error:'basket_quantity_failed',detail:error.message},400);return json(req,{ok:true,cart:data})}
  if(action==='send_text'){
    const message=clean(body?.message,500);if(!message)return json(req,{ok:false,error:'message_required'},400);const {data:inbound,error:inboundError}=await sb.from('messages').insert({conversation_id:session.conversation_id,direction:'inbound',message_type:'text',body_text:message,raw_event:{source:'shopping_room',session_id:session.id}}).select('id').single();if(inboundError)return json(req,{ok:false,error:'message_save_failed'},500);
    const {data:conv}=await sb.from('conversations').select('mode').eq('id',session.conversation_id).maybeSingle();if(conv?.mode!=='ai')return json(req,{ok:true,reply:'Para continuar com nossa equipe, toque em Continuar pelo WhatsApp.',ui:{type:'human'}});
    const intent=intentFor(message);if(intent.type==='search'){const {data:cfg}=await sb.from('automation_config').select('automation_enabled,ai_enabled,conversation_worker_enabled').eq('id',1).maybeSingle();if(cfg?.automation_enabled&&cfg?.ai_enabled&&cfg?.conversation_worker_enabled){const {data:job,error}=await sb.rpc('queue_ai_job_for_message',{p_message_id:inbound.id,p_job_type:'conversation',p_input:{source:'shopping_room'}});if(error)return json(req,{ok:false,error:'message_queue_failed'},500);return json(req,{ok:true,reply:null,ui:{type:'none'},ai_job:job});}}
    let reply='Certo. Vou te ajudar por aqui.';let ui:any={type:'none'};if(intent.type==='decline_upsell'){reply='Perfeito. Vou focar somente no que você já escolheu.';ui={type:'checkout_hint'};if(session.conversation_id)await sb.from('conversations').update({upsell_declined:true,sales_pressure_level:0,updated_at:new Date().toISOString()}).eq('id',session.conversation_id)}else if(intent.type==='fast_checkout'){reply='Claro. Vou direto para a conferência do pedido.';ui={type:'checkout'};if(session.conversation_id)await sb.from('conversations').update({fast_checkout:true,sales_pressure_level:0,updated_at:new Date().toISOString()}).eq('id',session.conversation_id)}else if(intent.type==='checkout'){reply='Vamos conferir seu pedido antes de confirmar.';ui={type:'checkout'}}else if(intent.type==='offers'){reply='Vou mostrar as ofertas disponíveis agora.';ui={type:'products',offers:true}}else if(intent.type==='baskets'){reply='Estas são as cestas disponíveis para encomenda.';ui={type:'baskets'}}else if(intent.type==='category'){reply='Separei essa seção para você escolher com calma.';ui={type:'products',category:(intent as any).category}}else{reply='Vou procurar produtos relacionados ao que você pediu.';ui={type:'products',q:(intent as any).q}}if(session.conversation_id)await sb.from('messages').insert({conversation_id:session.conversation_id,direction:'outbound',message_type:'text',body_text:reply,ai_interpretation:{source:'deterministic_room_router',intent},raw_event:{source:'shopping_room',session_id:session.id}});await sb.from('catalog_sessions').update({last_activity_at:new Date().toISOString()}).eq('id',session.id);return json(req,{ok:true,reply,ui,intent});
  }
  if(action==='checkout_preview'){const {data,error}=await sb.rpc('room_checkout_preview',{p_public_token:token});if(error)return json(req,{ok:false,error:'checkout_failed',detail:error.message},400);return json(req,{ok:true,checkout:data})}
  if(action==='confirm_order'){const address=body?.delivery_address&&typeof body.delivery_address==='object'?body.delivery_address:{};const {data,error}=await sb.rpc('room_confirm_order',{p_public_token:token,p_delivery_address:address});if(error)return json(req,{ok:false,error:'confirm_failed',detail:error.message},400);const {data:draft}=await sb.rpc('build_bling_order_draft',{p_order_id:data.order_id});return json(req,{ok:true,order:data,erp_status:'pending_integration',bling_draft_ready:!!draft,whatsapp_url:await whatsappUrl(`Meu pedido foi confirmado na Sala de Compra. Pedido ${data.order_id}.`)})}
  if(action==='return_whatsapp'){await sb.from('catalog_events').insert({catalog_session_id:session.id,customer_id:session.customer_id,event_type:'catalog_checkout_return',event_data:{source:'shopping_room',without_checkout:true}});return json(req,{ok:true,whatsapp_url:await whatsappUrl('Quero continuar meu pedido pelo WhatsApp.')})}
  return json(req,{ok:false,error:'unknown_action'},400);
});
