(function(){
  'use strict';
  const C=window.DA_SETUP_ADMIN_CONFIG||{};
  const $=id=>document.getElementById(id);
  const status=(text,kind='')=>{const el=$('status');el.textContent=text;el.className=`status ${kind}`.trim()};
  const fields=()=>({display_name:$('name').value.trim()||'Administrador',email:$('email').value.trim().toLowerCase(),password:$('password').value,bootstrap_code:$('code').value.trim()});
  function validate(v){if(!v.email||!v.password||!v.bootstrap_code)throw new Error('Preencha e-mail, senha e código de ativação.');if(v.password.length<10)throw new Error('A senha precisa ter pelo menos 10 caracteres.');}
  async function auth(path,body){const r=await fetch(`${C.supabaseUrl}/auth/v1/${path}`,{method:'POST',headers:{apikey:C.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error_description||data.msg||data.message||`Erro ${r.status}`);return data;}
  async function activate(accessToken,v){const r=await fetch(`${C.supabaseUrl}/functions/v1/${C.bootstrapFunction}`,{method:'POST',headers:{apikey:C.supabasePublishableKey,Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({bootstrap_code:v.bootstrap_code,display_name:v.display_name})});const data=await r.json().catch(()=>({}));if(!r.ok||data.ok===false){const labels={invalid_bootstrap_code:'Código de ativação inválido.',bootstrap_closed:'A ativação inicial já foi encerrada.',unauthorized:'Sessão não autorizada.'};throw new Error(labels[data.error]||data.detail||data.error||`Erro ${r.status}`)}return data;}
  async function createAndActivate(){const v=fields();validate(v);setBusy(true);status('Criando a conta…');try{let data=await auth('signup',{email:v.email,password:v.password,data:{display_name:v.display_name}});let token=data.access_token;if(!token){status('A conta foi criada, mas o Supabase solicitou confirmação de e-mail. Confirme o e-mail e depois use “Já tenho a conta”.');return;}status('Conta criada. Ativando proprietário…');await activate(token,v);status('Pronto. Você é o proprietário do Admin v3. Já pode entrar no painel.','ok');$('code').value='';}catch(e){status(e.message,'err')}finally{setBusy(false)}}
  async function loginAndActivate(){const v=fields();validate(v);setBusy(true);status('Entrando…');try{const data=await auth('token?grant_type=password',{email:v.email,password:v.password});if(!data.access_token)throw new Error('Login não retornou sessão.');status('Ativando proprietário…');await activate(data.access_token,v);status('Pronto. Você é o proprietário do Admin v3.','ok');$('code').value='';}catch(e){status(e.message,'err')}finally{setBusy(false)}}
  function setBusy(value){$('create').disabled=value;$('login').disabled=value}
  $('create').addEventListener('click',createAndActivate);$('login').addEventListener('click',loginAndActivate);
})();
