import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,"Content-Type":"application/json","Cache-Control":"no-store"}});
const text=(v:unknown,m=1000)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,m);
const num=(v:unknown)=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
const integer=(v:unknown,min=-100000,max=100000)=>Math.min(max,Math.max(min,Number.parseInt(String(v??0),10)||0));
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({ok:false,error:"server_config"},500);
 const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({ok:false,error:"unauthorized"},401);
 const sb=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const {data:ud}=await sb.auth.getUser(token);if(!ud?.user?.id)return json({ok:false,error:"unauthorized"},401);const user=ud.user;
 const {data:admin}=await sb.from("admin_users").select("role,is_active").eq("user_id",user.id).maybeSingle();if(!admin?.is_active)return json({ok:false,error:"admin_not_authorized"},403);const canWrite=admin.role==='owner'||admin.role==='operator';
 let body:any;try{body=await req.json()}catch{body={}}const action=text(body?.action||'list',50).toLowerCase();
 if(action==='list'){
   const q=text(body?.q,100);let query=sb.from('basket_templates').select('id,sku,name,description,image_url,base_price,is_active,is_whatsapp_active,is_featured,sort_order,rules,updated_at,basket_template_items(count)',{count:'exact'}).order('sort_order',{ascending:true}).order('name',{ascending:true});
   if(q){const safe=q.replace(/[,%()]/g,' ').trim();if(safe)query=query.or(`name.ilike.%${safe}%,sku.ilike.%${safe}%`)}const {data,error,count}=await query;if(error)return json({ok:false,error:'list_failed',detail:error.message},400);return json({ok:true,baskets:data||[],total:count||0});
 }
 if(action==='get'){
   const id=text(body?.id,80);if(!id)return json({ok:false,error:'id_required'},400);const {data:basket,error}=await sb.from('basket_templates').select('*').eq('id',id).maybeSingle();if(error||!basket)return json({ok:false,error:'basket_not_found'},404);
   const {data:items}=await sb.from('basket_template_items').select('id,quantity,removable,quantity_editable,min_quantity,max_quantity,substitution_group,pricing_rule,sort_order,product:products(id,name,sku,gtin,image_url,brand,packaging,stock,price,is_active,physically_verified)').eq('basket_id',id).order('sort_order',{ascending:true}).order('created_at',{ascending:true});
   const {data:changes}=await sb.from('basket_changes').select('id,change_type,detail,created_at').eq('basket_id',id).order('created_at',{ascending:false}).limit(20);return json({ok:true,basket,items:items||[],changes:changes||[]});
 }
 if(action==='save'){
   if(!canWrite)return json({ok:false,error:'read_only'},403);const id=text(body?.id,80);const name=text(body?.name,180);const price=num(body?.base_price);if(!name)return json({ok:false,error:'name_required'},400);if(price===null||price<0)return json({ok:false,error:'invalid_base_price'},400);
   const row:any={name,sku:text(body?.sku,100)||null,description:text(body?.description,3000)||null,image_url:text(body?.image_url,1200)||null,base_price:price,is_active:body?.is_active!==false,is_whatsapp_active:body?.is_whatsapp_active!==false,is_featured:body?.is_featured===true,sort_order:integer(body?.sort_order),internal_notes:text(body?.internal_notes,3000)||null,updated_by:user.id,updated_at:new Date().toISOString()};
   if(id){const {data:before}=await sb.from('basket_templates').select('*').eq('id',id).maybeSingle();if(!before)return json({ok:false,error:'basket_not_found'},404);const {data,error}=await sb.from('basket_templates').update(row).eq('id',id).select('*').single();if(error)return json({ok:false,error:'save_failed',detail:error.message},400);await sb.from('basket_changes').insert({basket_id:id,changed_by:user.id,change_type:'edit_basket',detail:{before:{name:before.name,base_price:before.base_price,is_active:before.is_active},after:{name:data.name,base_price:data.base_price,is_active:data.is_active}}});return json({ok:true,basket:data});}
   const {data,error}=await sb.from('basket_templates').insert(row).select('*').single();if(error)return json({ok:false,error:'save_failed',detail:error.message},400);await sb.from('basket_changes').insert({basket_id:data.id,changed_by:user.id,change_type:'create_basket',detail:{name:data.name,base_price:data.base_price}});return json({ok:true,basket:data});
 }
 if(action==='search_products'){
   const q=text(body?.q,100);if(q.length<2)return json({ok:true,products:[]});const safe=q.replace(/[,%()]/g,' ').trim();let query=sb.from('products').select('id,name,sku,gtin,image_url,brand,packaging,stock,price,is_active,physically_verified').eq('physically_verified',true).eq('is_active',true).limit(30);if(safe)query=query.or(`name.ilike.%${safe}%,gtin.ilike.%${safe}%,sku.ilike.%${safe}%,brand.ilike.%${safe}%`);const {data,error}=await query;if(error)return json({ok:false,error:'product_search_failed',detail:error.message},400);return json({ok:true,products:data||[]});
 }
 if(action==='add_item'){
   if(!canWrite)return json({ok:false,error:'read_only'},403);const basketId=text(body?.basket_id,80),productId=text(body?.product_id,80),qty=num(body?.quantity);if(!basketId||!productId)return json({ok:false,error:'ids_required'},400);if(qty===null||qty<=0)return json({ok:false,error:'invalid_quantity'},400);const {data:p}=await sb.from('products').select('id,name,physically_verified').eq('id',productId).maybeSingle();if(!p?.physically_verified)return json({ok:false,error:'product_not_verified'},409);const {data:existing}=await sb.from('basket_template_items').select('id,quantity').eq('basket_id',basketId).eq('product_id',productId).maybeSingle();let item:any;if(existing){const {data,error}=await sb.from('basket_template_items').update({quantity:qty}).eq('id',existing.id).select('*').single();if(error)return json({ok:false,error:'item_save_failed',detail:error.message},400);item=data}else{const {data,error}=await sb.from('basket_template_items').insert({basket_id:basketId,product_id:productId,quantity:qty,removable:body?.removable!==false,quantity_editable:body?.quantity_editable!==false,min_quantity:num(body?.min_quantity)??0,max_quantity:num(body?.max_quantity),substitution_group:text(body?.substitution_group,120)||null,sort_order:integer(body?.sort_order)}).select('*').single();if(error)return json({ok:false,error:'item_save_failed',detail:error.message},400);item=data}await sb.from('basket_changes').insert({basket_id:basketId,changed_by:user.id,change_type:'add_or_update_item',detail:{product_id:productId,product_name:p.name,quantity:qty}});return json({ok:true,item});
 }
 if(action==='update_item'){
   if(!canWrite)return json({ok:false,error:'read_only'},403);const id=text(body?.id,80);const {data:before}=await sb.from('basket_template_items').select('*').eq('id',id).maybeSingle();if(!before)return json({ok:false,error:'item_not_found'},404);const patch:any={};if(body?.quantity!==undefined){const q=num(body.quantity);if(q===null||q<=0)return json({ok:false,error:'invalid_quantity'},400);patch.quantity=q}if(typeof body?.removable==='boolean')patch.removable=body.removable;if(typeof body?.quantity_editable==='boolean')patch.quantity_editable=body.quantity_editable;if(body?.min_quantity!==undefined)patch.min_quantity=num(body.min_quantity)??0;if(body?.max_quantity!==undefined)patch.max_quantity=num(body.max_quantity);if(body?.substitution_group!==undefined)patch.substitution_group=text(body.substitution_group,120)||null;if(body?.sort_order!==undefined)patch.sort_order=integer(body.sort_order);const {data,error}=await sb.from('basket_template_items').update(patch).eq('id',id).select('*').single();if(error)return json({ok:false,error:'item_save_failed',detail:error.message},400);await sb.from('basket_changes').insert({basket_id:before.basket_id,changed_by:user.id,change_type:'edit_item',detail:{item_id:id,before,after:data}});return json({ok:true,item:data});
 }
 if(action==='remove_item'){
   if(!canWrite)return json({ok:false,error:'read_only'},403);const id=text(body?.id,80);const {data:before}=await sb.from('basket_template_items').select('id,basket_id,product_id,quantity').eq('id',id).maybeSingle();if(!before)return json({ok:false,error:'item_not_found'},404);const {error}=await sb.from('basket_template_items').delete().eq('id',id);if(error)return json({ok:false,error:'remove_failed',detail:error.message},400);await sb.from('basket_changes').insert({basket_id:before.basket_id,changed_by:user.id,change_type:'remove_item',detail:before});return json({ok:true});
 }
 return json({ok:false,error:'unknown_action'},400);
});
