(function(){
'use strict';
const C=window.DA_ADMIN_V3_CONFIG||{},AUTH_KEY='da_admin_v3_auth';let root=null,state={workflows:[],selected:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]));
function auth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
async function refresh(a){const r=await fetch(`${C.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:C.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:a?.refresh_token})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error('Sessão expirada.');localStorage.setItem(AUTH_KEY,JSON.stringify(d));return d}
async function api(action,payload={},retry=true){let a=auth();if(!a?.access_token)throw new Error('Faça login.');const r=await fetch(`${C.supabaseUrl}/functions/v1/${C.automationBuilderEdgeFunction||'admin-automation-builder-v1'}`,{method:'POST',headers:{apikey:C.supabasePublishableKey,Authorization:`Bearer ${a.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(r.status===401&&retry){await refresh(a);return api(action,payload,false)}if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||`Erro ${r.status}`);return d}
function toast(m,k=''){const box=document.getElementById('toastRegion');if(!box)return;const x=document.createElement('div');x.className=`toast ${k}`.trim();x.textContent=m;box.appendChild(x);setTimeout(()=>x.remove(),4500)}
function shell(){return `<section class="automation-builder"><div class="automation-note automation-danger"><strong>Motor geral em modo dormente.</strong> Não há ativação de runtime, aumento de canary, desligamento de kill switch ou execução externa.</div><div class="automation-grid"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Linguagem natural</div><h2>Gerar workflow revisável</h2></div><span class="automation-pill off">draft only</span></div><form id="autoCompileForm" class="automation-canvas"><label>Descreva a automação<textarea id="autoInstruction" rows="5" placeholder="Ex.: Todo dia gere um snapshot de produtos com estoque baixo para revisão."></textarea></label><button class="button primary" type="submit">Compilar rascunho</button><pre id="autoCompileResult" class="exp-preview">Nenhuma compilação. Esta operação não cria workflow nem chama runtime.</pre></form></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">Custo / execução</div><h2>Recomendador</h2></div></div><form id="autoStrategyForm" class="automation-canvas"><label>Trigger<select id="autoTrigger"><option>schedule</option><option>inventory</option><option>expiry</option><option>anomaly</option><option>conversation</option><option>order</option></select></label><label><input id="autoRealtime" type="checkbox"> Requer realtime</label><label><input id="autoExternal" type="checkbox"> Conector externo indispensável</label><button class="button secondary" type="submit">Recomendar</button><pre id="autoStrategyResult" class="exp-preview">GitHub Actions primeiro para batch determinístico.</pre></form></section></div><section class="panel"><div class="panel-head"><div><div class="eyebrow">Workflows</div><h2>TRIGGER → CONDITIONS → ACTIONS</h2></div><button id="autoReload" class="button secondary small" type="button">Atualizar</button></div><div id="autoList" class="automation-workflow-list"></div></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">Simulador</div><h2 id="autoSelectedTitle">Selecione um workflow</h2></div><span id="autoSelectedState" class="automation-pill off">off</span></div><div id="autoCanvas" class="automation-canvas"><div class="empty">Nenhum workflow selecionado.</div></div></section></section>`}
function renderList(){const b=root.querySelector('#autoList');b.innerHTML=state.workflows.length?state.workflows.map(w=>`<button class="automation-workflow-button" data-id="${esc(w.id)}" type="button"><strong>${esc(w.display_name)}</strong><small>${esc(w.trigger_type)} · ${esc(w.execution_strategy)} · v${esc(w.current_version)}</small><small>${w.enabled?'enabled':'disabled'} / ${esc(w.execution_mode)} / kill ${w.kill_switch?'ON':'OFF'}</small></button>`).join(''):'<div class="empty">Nenhum workflow.</div>';b.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>select(x.dataset.id))}
function select(id){state.selected=state.workflows.find(x=>x.id===id)||null;const w=state.selected,title=root.querySelector('#autoSelectedTitle'),badge=root.querySelector('#autoSelectedState'),box=root.querySelector('#autoCanvas');if(!w)return;title.textContent=w.display_name;badge.textContent=w.execution_mode;box.innerHTML=`<div class="automation-node"><strong>TRIGGER · ${esc(w.trigger_type)}</strong><small>${esc(JSON.stringify(w.trigger_config||{}))}</small></div><div class="automation-node"><strong>CONDITIONS · ${(w.conditions||[]).length}</strong><small>${esc(JSON.stringify(w.conditions||[]))}</small></div><div class="automation-node"><strong>ACTIONS · ${(w.actions||[]).length}</strong><small>${esc(JSON.stringify(w.actions||[]))}</small></div><div class="automation-actions"><button id="autoValidate" class="button secondary" type="button">Validar</button><button id="autoSimulate" class="button primary" type="button">Simular sem efeitos</button><button id="autoKill" class="button danger" type="button">Aplicar kill switch</button></div><pre id="autoSimulation" class="exp-preview">Simulação revalida handoff e Action Registry.</pre>`;root.querySelector('#autoValidate').onclick=validate;root.querySelector('#autoSimulate').onclick=simulate;root.querySelector('#autoKill').onclick=kill}
async function load(){const d=await api('list');state.workflows=d.workflows||[];renderList();if(state.selected)select(state.selected.id)}
async function compile(e){e.preventDefault();try{const instruction=root.querySelector('#autoInstruction').value.trim();const d=await api('compile_draft',{instruction});root.querySelector('#autoCompileResult').textContent=JSON.stringify(d.draft,null,2)}catch(err){root.querySelector('#autoCompileResult').textContent=`Bloqueado: ${err.message}`}}
async function strategy(e){e.preventDefault();try{const d=await api('recommend_strategy',{trigger_type:root.querySelector('#autoTrigger').value,requires_realtime:root.querySelector('#autoRealtime').checked,external_connector:root.querySelector('#autoExternal').checked,deterministic:true});root.querySelector('#autoStrategyResult').textContent=JSON.stringify(d.recommendation,null,2)}catch(err){toast(err.message,'error')}}
async function validate(){try{const d=await api('validate',{workflow_id:state.selected.id});root.querySelector('#autoSimulation').textContent=JSON.stringify(d.validation,null,2)}catch(e){toast(e.message,'error')}}
async function simulate(){try{const d=await api('simulate',{workflow_id:state.selected.id,input:{source:'admin_stage10_preview'},has_open_handoff:true,idempotency_key:`preview:${state.selected.id}`});root.querySelector('#autoSimulation').textContent=JSON.stringify(d.simulation,null,2)}catch(e){toast(e.message,'error')}}
async function kill(){try{await api('kill',{workflow_id:state.selected.id});toast('Kill switch aplicado.');await load()}catch(e){toast(e.message,'error')}}
async function mount(el){root=el;root.innerHTML=shell();root.querySelector('#autoReload').onclick=()=>load().catch(e=>toast(e.message,'error'));root.querySelector('#autoCompileForm').onsubmit=compile;root.querySelector('#autoStrategyForm').onsubmit=strategy;await load().catch(e=>toast(e.message,'error'))}
window.DAAutomationBuilder={mount};
})();