(function(){
  'use strict';
  const C=window.DA_ADMIN_V3_CONFIG||{},AUTH_KEY='da_admin_v3_auth';
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  let root=null,state={workflows:[],catalog:null,selected:null};
  function auth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
  async function refreshToken(a){const r=await fetch(`${C.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:C.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:a?.refresh_token})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error('Sessão expirada.');localStorage.setItem(AUTH_KEY,JSON.stringify(d));return d}
  async function api(action,payload={},retry=true){let a=auth();if(!a?.access_token)throw new Error('Faça login.');const r=await fetch(`${C.supabaseUrl}/functions/v1/${C.automationBuilderEdgeFunction||'admin-automation-builder-v1'}`,{method:'POST',headers:{apikey:C.supabasePublishableKey,Authorization:`Bearer ${a.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(r.status===401&&retry){await refreshToken(a);return api(action,payload,false)}if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||`Erro ${r.status}`);return d}
  function toast(msg,kind=''){const region=document.getElementById('toastRegion');if(!region)return;const x=document.createElement('div');x.className=`toast ${kind}`.trim();x.textContent=msg;region.appendChild(x);setTimeout(()=>x.remove(),4000)}
  const pill=(v,extra='')=>`<span class="automation-pill ${esc(extra||v)}">${esc(v)}</span>`;
  function shell(){return `<section class="automation-builder">
    <div class="automation-note automation-danger"><strong>Motor geral em modo dormente.</strong> Este painel não possui ação para ativar runtime, elevar canary, desligar kill switch ou executar efeitos externos.</div>
    <div class="automation-grid">
      <section class="panel"><div class="panel-head"><div><div class="eyebrow">Workflows</div><h2>TRIGGER → CONDITIONS → ACTIONS</h2></div><button id="autoReload" class="button secondary small" type="button">Atualizar</button></div><div id="autoList" class="automation-workflow-list"></div></section>
      <section class="panel"><div class="panel-head"><div><div class="eyebrow">Custo / execução</div><h2>Recomendador de estratégia</h2></div></div><form id="autoStrategyForm" class="automation-canvas"><label>Trigger<select id="autoTrigger"><option>schedule</option><option>inventory</option><option>anomaly</option><option>conversation</option><option>order</option></select></label><label><input id="autoRealtime" type="checkbox"> Requer realtime</label><label><input id="autoExternal" type="checkbox"> Conector externo indispensável</label><button class="button secondary" type="submit">Recomendar estratégia</button><pre id="autoStrategyResult" class="exp-preview">GitHub Actions é a preferência para batch determinístico e não urgente.</pre></form></section>
    </div>
    <section class="panel"><div class="panel-head"><div><div class="eyebrow">Simulador</div><h2 id="autoSelectedTitle">Selecione um workflow</h2></div><span id="autoSelectedState" class="automation-pill off">off</span></div><div id="autoCanvas" class="automation-canvas"><div class="empty">Nenhum workflow selecionado.</div></div></section>
  </section>`}
  function renderList(){const box=root.querySelector('#autoList');box.innerHTML=state.workflows.length?state.workflows.map(w=>`<button class="automation-workflow-button" data-workflow="${esc(w.id)}" type="button"><strong>${esc(w.display_name)}</strong><small>${esc(w.trigger_type)} · ${esc(w.execution_strategy)} · v${esc(w.current_version)}</small><small>${w.enabled?'enabled':'disabled'} / ${esc(w.execution_mode)} / kill ${w.kill_switch?'ON':'OFF'}</small></button>`).join(''):'<div class="empty">Nenhum workflow.</div>';box.querySelectorAll('[data-workflow]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.workflow)))}
  function renderSelected(){const w=state.selected,title=root.querySelector('#autoSelectedTitle'),badge=root.querySelector('#autoSelectedState'),box=root.querySelector('#autoCanvas');if(!w){title.textContent='Selecione um workflow';badge.textContent='off';box.innerHTML='<div class="empty">Nenhum workflow selecionado.</div>';return}title.textContent=w.display_name;badge.textContent=w.execution_mode;badge.className=`automation-pill ${w.execution_mode}`;const actions=(w.actions||[]).map(a=>`<div class="automation-node"><header><strong>ACTION · ${esc(a.action_key||'—')}</strong>${pill('governada')}</header><small>Referência obrigatória ao AI Action Registry.</small></div>`).join('')||'<div class="automation-node"><strong>ACTIONS</strong><small>Nenhuma ação definida.</small></div>';box.innerHTML=`<div class="automation-node"><header><strong>TRIGGER · ${esc(w.trigger_type)}</strong>${pill(w.execution_strategy,w.execution_strategy)}</header><small>${esc(JSON.stringify(w.trigger_config||{}))}</small></div><div class="automation-node"><header><strong>CONDITIONS</strong>${pill(String((w.conditions||[]).length))}</header><small>${esc(JSON.stringify(w.conditions||[]))}</small></div>${actions}<div class="automation-actions"><button id="autoValidate" class="button secondary" type="button">Validar</button><button id="autoSimulate" class="button primary" type="button">Simular sem efeitos</button><button id="autoKill" class="button danger" type="button">Aplicar kill switch</button></div><pre id="autoSimulation" class="exp-preview">Nenhum side effect será executado.</pre>`;root.querySelector('#autoValidate').onclick=validate;root.querySelector('#autoSimulate').onclick=simulate;root.querySelector('#autoKill').onclick=kill}
  function select(id){state.selected=state.workflows.find(x=>x.id===id)||null;renderSelected()}
  async function load(){const [list,catalog]=await Promise.all([api('list'),api('catalog')]);state.workflows=list.workflows||[];state.catalog=catalog;renderList();if(state.selected)select(state.selected.id)}
  async function validate(){try{const d=await api('validate',{workflow_id:state.selected.id});root.querySelector('#autoSimulation').textContent=JSON.stringify(d.validation,null,2)}catch(e){toast(e.message,'error')}}
  async function simulate(){try{const d=await api('simulate',{workflow_id:state.selected.id,input:{source:'admin_stage10_preview'},has_open_handoff:true,idempotency_key:`preview:${state.selected.id}`});root.querySelector('#autoSimulation').textContent=JSON.stringify(d.simulation,null,2)}catch(e){toast(e.message,'error')}}
  async function kill(){try{await api('kill',{workflow_id:state.selected.id});toast('Kill switch aplicado.');await load();select(state.selected?.id)}catch(e){toast(e.message,'error')}}
  async function strategy(ev){ev.preventDefault();try{const d=await api('recommend_strategy',{trigger_type:root.querySelector('#autoTrigger').value,requires_realtime:root.querySelector('#autoRealtime').checked,external_connector:root.querySelector('#autoExternal').checked,deterministic:true});root.querySelector('#autoStrategyResult').textContent=JSON.stringify(d.recommendation,null,2)}catch(e){toast(e.message,'error')}}
  async function mount(el){root=el;root.innerHTML=shell();root.querySelector('#autoReload').onclick=()=>load().catch(e=>toast(e.message,'error'));root.querySelector('#autoStrategyForm').onsubmit=strategy;await load().catch(e=>toast(e.message,'error'))}
  window.DAAutomationBuilder={mount};
})();
