(function(){
'use strict';
const C=window.DA_ADMIN_V3_CONFIG||{};const AUTH_KEY='da_admin_v3_auth';const $=id=>document.getElementById(id);const txt=v=>String(v??'').trim();const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
let productData=null,basketData=null,basketTimer=null;
function auth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
async function call(functionName,action,payload={},retry=true){let a=auth();if(!a?.access_token)throw new Error('Faça login novamente.');let r=await fetch(`${C.supabaseUrl}/functions/v1/${functionName}`,{method:'POST',headers:{apikey:C.supabasePublishableKey,Authorization:`Bearer ${a.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});let data=await r.json().catch(()=>({}));if(r.status===401&&retry&&a.refresh_token){const rr=await fetch(`${C.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:C.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:a.refresh_token})});const fresh=await rr.json().catch(()=>({}));if(rr.ok&&fresh.access_token){localStorage.setItem(AUTH_KEY,JSON.stringify(fresh));return call(functionName,action,payload,false)}}if(!r.ok||data.ok===false)throw new Error(data.detail||labelError(data.error)||data.error||`Erro ${r.status}`);return data}
const ops=(action,payload)=>call(C.edgeFunction||'admin-ops-v1',action,payload);const baskets=(action,payload)=>call('admin-baskets-v1',action,payload);
function labelError(code){return({invalid_gtin:'EAN/GTIN inválido.',invalid_ncm:'NCM precisa ter 8 dígitos.',already_in_bling:'Este produto já está vinculado ao Bling.',product_incomplete:'Produto incompleto para cadastro no Bling.',product_not_verified:'Só produtos fisicamente conferidos podem entrar na cesta.',invalid_base_price:'Informe um preço válido para a cesta.'})[code]||''}
function toast(message,kind=''){const host=$('toastRegion');if(!host)return;const n=document.createElement('div');n.className=`toast ${kind}`.trim();n.textContent=message;host.appendChild(n);setTimeout(()=>n.remove(),kind==='error'?6500:3500)}
function modal(title,eyebrow='Edição'){$('modalTitle').textContent=title;$('modalEyebrow').textContent=eyebrow;$('modalBody').innerHTML='<div class="empty">Carregando…</div>';$('modalFooter').innerHTML='';$('modalBackdrop').classList.remove('hidden');$('modal').classList.remove('hidden')}
function closeModal(){$('modalBackdrop').classList.add('hidden');$('modal').classList.add('hidden')}
function field(label,id,value='',type='text',extra=''){return `<label class="edit-field"><span>${esc(label)}</span><input id="${id}" type="${type}" value="${esc(value??'')}" ${extra}></label>`}
function check(label,id,checked){return `<label class="check-field"><input id="${id}" type="checkbox" ${checked?'checked':''}><span>${esc(label)}</span></label>`}
function val(id){return $(id)?.value??''}function checked(id){return !!$(id)?.checked}

async function openEditableProduct(id){modal('Produto','Gestão de produto');try{productData=await ops('product',{id});renderProductEditor()}catch(e){$('modalBody').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderProductEditor(){const p=productData.product||{};const counts=productData.count_history||[],commands=productData.commands||[];$('modalTitle').textContent=p.name||'Produto';
 $('modalBody').innerHTML=`<div class="product-editor-head">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:''}<div><strong>${esc(p.name)}</strong><small>EAN ${esc(p.gtin||'—')} · Bling ${esc(p.bling_product_id||'não vinculado')} · estoque contado ${esc(p.stock??0)}</small></div></div>
 <div class="editor-note">O estoque não é alterado nesta tela. Para manter o saldo confiável, use a <a href="../contagem-v2/">contagem física</a>.</div>
 <div class="edit-grid">${field('Nome','ep_name',p.name)}${field('SKU / código','ep_sku',p.sku)}${field('EAN / GTIN','ep_gtin',p.gtin,'text','inputmode="numeric"')}${field('NCM','ep_ncm',p.ncm,'text','inputmode="numeric"')}${field('Preço de venda','ep_price',p.price??'','number','min="0" step="0.01"')}${field('Preço de custo','ep_cost',p.cost??'','number','min="0" step="0.01"')}${field('Marca','ep_brand',p.brand)}${field('Unidade','ep_unit',p.unit||'UN')}${field('Categoria','ep_category',p.category)}${field('Subcategoria','ep_subcategory',p.subcategory)}${field('Embalagem','ep_packaging',p.packaging)}${field('Validade','ep_validity',p.validity_date||'','date')}${field('Gôndola','ep_gondola',p.gondola)}${field('Prateleira','ep_shelf',p.shelf)}${field('Estoque mínimo','ep_min_stock',p.min_stock??'','number','min="0" step="1"')}${field('Ordem','ep_sort_order',p.sort_order??0,'number')}${field('Categoria WhatsApp','ep_wa_category',p.whatsapp_category)}${field('URL da imagem','ep_image',p.image_url)}<label class="edit-field span2"><span>Descrição curta</span><textarea id="ep_desc_short">${esc(p.description_short||'')}</textarea></label><label class="edit-field span2"><span>Descrição completa</span><textarea id="ep_desc_long" rows="4">${esc(p.description_long||'')}</textarea></label><label class="edit-field span2"><span>Tags (separadas por vírgula)</span><input id="ep_tags" value="${esc((p.tags||[]).join(', '))}"></label></div>
 <div class="checks">${check('Produto ativo','ep_active',p.is_active!==false)}${check('Mostrar no WhatsApp','ep_whatsapp',p.is_whatsapp_active===true)}${check('Oferta','ep_offer',p.is_offer===true)}${check('Usar em upsell','ep_upsell',p.is_upsell===true)}</div>
 <div class="detail-strip"><span>Sync: <strong>${esc(p.sync_status||'local')}</strong></span><span>Última contagem: <strong>${esc(p.last_counted_at?new Date(p.last_counted_at).toLocaleString('pt-BR'):'—')}</strong></span></div>
 <h3 class="editor-title">Últimas contagens</h3><div class="mini-history">${counts.length?counts.slice(0,8).map(h=>`<div><span>${new Date(h.counted_at).toLocaleString('pt-BR')}</span><strong>${esc(h.previous_stock??'—')} → ${esc(h.counted_stock)}</strong><em>${esc(h.sync_status)}</em></div>`).join(''):'<div class="empty">Sem contagens.</div>'}</div>
 <h3 class="editor-title">Integração Bling</h3><div class="mini-history">${commands.length?commands.slice(0,8).map(c=>`<div><span>${esc(c.command_type)}</span><strong>${esc(c.status)}</strong><em>${esc(c.error_message||'')}</em></div>`).join(''):'<div class="empty">Sem comandos.</div>'}</div>`;
 $('modalFooter').innerHTML=`<button class="button secondary" data-enh-close type="button">Fechar</button>${!p.bling_product_id?'<button class="button secondary" id="ep_create_bling" type="button">Cadastrar no Bling</button>':''}<button class="button primary" id="ep_save" type="button">Salvar alterações</button>`;
 $('ep_save').onclick=saveProduct;if($('ep_create_bling'))$('ep_create_bling').onclick=queueCreateProduct;
}
async function saveProduct(){const p=productData.product;const patch={name:val('ep_name'),sku:val('ep_sku'),gtin:val('ep_gtin'),ncm:val('ep_ncm'),price:val('ep_price'),cost:val('ep_cost'),brand:val('ep_brand'),unit:val('ep_unit'),category:val('ep_category'),subcategory:val('ep_subcategory'),packaging:val('ep_packaging'),validity_date:val('ep_validity')||null,gondola:val('ep_gondola'),shelf:val('ep_shelf'),min_stock:val('ep_min_stock')||null,sort_order:val('ep_sort_order'),whatsapp_category:val('ep_wa_category'),image_url:val('ep_image'),description_short:val('ep_desc_short'),description_long:val('ep_desc_long'),tags:val('ep_tags').split(',').map(x=>x.trim()).filter(Boolean),is_active:checked('ep_active'),is_whatsapp_active:checked('ep_whatsapp'),is_offer:checked('ep_offer'),is_upsell:checked('ep_upsell')};const b=$('ep_save');b.disabled=true;b.textContent='Salvando…';try{const data=await ops('update_product',{id:p.id,patch});toast(data.changed?.length?`Produto salvo · ${data.changed.length} campo(s) alterado(s).`:'Nenhuma alteração.','success');productData=await ops('product',{id:p.id});renderProductEditor();$('refreshButton')?.click()}catch(e){toast(e.message,'error')}finally{if($('ep_save')){$('ep_save').disabled=false;$('ep_save').textContent='Salvar alterações'}}}
async function queueCreateProduct(){const p=productData.product;if(!confirm(`Cadastrar “${p.name}” no Bling como produto novo? Use somente se ele realmente não existir no ERP.`))return;const b=$('ep_create_bling');b.disabled=true;try{await ops('queue_create_product',{id:p.id});toast('Cadastro colocado na fila do Bling.','success');productData=await ops('product',{id:p.id});renderProductEditor()}catch(e){toast(e.message,'error')}finally{if($('ep_create_bling'))$('ep_create_bling').disabled=false}}

async function loadBaskets(){const host=$('basketRows');if(!host)return;host.innerHTML='<div class="empty">Carregando…</div>';try{const data=await baskets('list',{q:val('basketSearch')});$('basketSummary').textContent=`${data.total||0} cesta(s)`;host.innerHTML=(data.baskets||[]).length?data.baskets.map(b=>`<article class="basket-card" data-open-basket="${esc(b.id)}"><div class="basket-image">${b.image_url?`<img src="${esc(b.image_url)}" alt="">`:'<span>🧺</span>'}</div><div class="basket-copy"><div class="basket-flags">${b.is_active?'<b>ATIVA</b>':'<b class="off">INATIVA</b>'}${b.is_whatsapp_active?'<b>WHATSAPP</b>':''}${b.is_featured?'<b>DESTAQUE</b>':''}</div><h3>${esc(b.name)}</h3><p>${esc(b.description||'')}</p><strong class="basket-price">${money(b.base_price)}</strong><small>${esc(b.sku||'Sem SKU')} · ${(b.basket_template_items?.[0]?.count)||0} item(ns)</small></div></article>`).join(''):'<div class="empty">Nenhuma cesta cadastrada.</div>'}catch(e){host.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderNewBasket(){basketData={basket:null,items:[]};modal('Nova cesta','Cadastro comercial');renderBasketEditor(true)}
async function openBasket(id){modal('Cesta','Gestão comercial');try{basketData=await baskets('get',{id});renderBasketEditor(false)}catch(e){$('modalBody').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderBasketEditor(isNew){const b=basketData.basket||{};const items=basketData.items||[];$('modalTitle').textContent=b.name||'Nova cesta';$('modalBody').innerHTML=`<div class="editor-note strong">O preço da cesta é comercial e independente da soma dos produtos. A diferença operacional será tratada como “Outras despesas” no pedido do Bling.</div><div class="edit-grid">${field('Nome','eb_name',b.name)}${field('SKU interno','eb_sku',b.sku)}${field('Preço comercial da cesta','eb_price',b.base_price??'','number','min="0" step="0.01"')}${field('Ordem','eb_sort',b.sort_order??0,'number')}${field('URL da foto quadrada','eb_image',b.image_url)}<label class="edit-field span2"><span>Descrição</span><textarea id="eb_description" rows="3">${esc(b.description||'')}</textarea></label><label class="edit-field span2"><span>Anotação interna</span><textarea id="eb_notes" rows="2">${esc(b.internal_notes||'')}</textarea></label></div><div class="checks">${check('Cesta ativa','eb_active',b.is_active!==false)}${check('Mostrar no WhatsApp','eb_whatsapp',b.is_whatsapp_active!==false)}${check('Destaque','eb_featured',b.is_featured===true)}</div>${isNew?'<div class="editor-note">Salve a cesta primeiro para adicionar os produtos.</div>':`<div class="basket-items-head"><div><h3>Composição</h3><small>O cliente verá nome e quantidade dos itens, não os preços individuais.</small></div><div class="product-search-mini"><input id="eb_product_search" placeholder="Adicionar por nome ou EAN"><div id="eb_product_results"></div></div></div><div id="eb_items" class="basket-items">${items.length?items.map(renderBasketItem).join(''):'<div class="empty">Nenhum produto na cesta.</div>'}</div>`}`;
 $('modalFooter').innerHTML=`<button class="button secondary" data-enh-close type="button">Fechar</button><button class="button primary" id="eb_save" type="button">${isNew?'Criar cesta':'Salvar cesta'}</button>`;$('eb_save').onclick=()=>saveBasket(isNew);if(!isNew&&$('eb_product_search')){$('eb_product_search').addEventListener('input',basketProductSearch);$('eb_items').addEventListener('click',basketItemClick);$('eb_items').addEventListener('change',basketItemChange)}}
function renderBasketItem(i){const p=i.product||{};return `<div class="basket-item" data-basket-item="${esc(i.id)}"><div class="basket-item-product">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:''}<div><strong>${esc(p.name||'Produto')}</strong><small>${esc([p.gtin,p.brand,p.packaging].filter(Boolean).join(' · '))}</small></div></div><label>Qtd<input data-item-qty type="number" min="0.001" step="1" value="${esc(i.quantity)}"></label><label class="tiny-check"><input data-item-removable type="checkbox" ${i.removable?'checked':''}>Pode retirar</label><label class="tiny-check"><input data-item-editable type="checkbox" ${i.quantity_editable?'checked':''}>Pode alterar qtd.</label><button data-remove-basket-item class="row-button danger-mini" type="button">Remover</button></div>`}
async function saveBasket(isNew){const payload={id:isNew?null:basketData.basket.id,name:val('eb_name'),sku:val('eb_sku'),base_price:val('eb_price'),sort_order:val('eb_sort'),image_url:val('eb_image'),description:val('eb_description'),internal_notes:val('eb_notes'),is_active:checked('eb_active'),is_whatsapp_active:checked('eb_whatsapp'),is_featured:checked('eb_featured')};const btn=$('eb_save');btn.disabled=true;try{const data=await baskets('save',payload);toast(isNew?'Cesta criada.':'Cesta salva.','success');basketData=await baskets('get',{id:data.basket.id});renderBasketEditor(false);loadBaskets()}catch(e){toast(e.message,'error')}finally{if($('eb_save'))$('eb_save').disabled=false}}
async function basketProductSearch(){clearTimeout(basketTimer);const q=val('eb_product_search');const host=$('eb_product_results');if(q.length<2){host.innerHTML='';return}basketTimer=setTimeout(async()=>{try{const data=await baskets('search_products',{q});host.innerHTML=(data.products||[]).map(p=>`<button data-add-basket-product="${esc(p.id)}" type="button"><strong>${esc(p.name)}</strong><small>${esc(p.gtin||p.sku||'')} · estoque ${esc(p.stock??0)}</small></button>`).join('')||'<div class="mini-empty">Nada encontrado.</div>';host.querySelectorAll('[data-add-basket-product]').forEach(b=>b.onclick=()=>addBasketProduct(b.dataset.addBasketProduct))}catch(e){host.innerHTML=`<div class="mini-empty">${esc(e.message)}</div>`}},220)}
async function addBasketProduct(productId){try{await baskets('add_item',{basket_id:basketData.basket.id,product_id:productId,quantity:1});basketData=await baskets('get',{id:basketData.basket.id});renderBasketEditor(false);toast('Produto adicionado.','success')}catch(e){toast(e.message,'error')}}
async function basketItemClick(e){const row=e.target.closest('[data-basket-item]');if(!row)return;if(e.target.closest('[data-remove-basket-item]')){if(!confirm('Remover este produto da cesta?'))return;try{await baskets('remove_item',{id:row.dataset.basketItem});basketData=await baskets('get',{id:basketData.basket.id});renderBasketEditor(false);toast('Produto removido.','success')}catch(err){toast(err.message,'error')}}}
async function basketItemChange(e){const row=e.target.closest('[data-basket-item]');if(!row)return;try{await baskets('update_item',{id:row.dataset.basketItem,quantity:row.querySelector('[data-item-qty]').value,removable:row.querySelector('[data-item-removable]').checked,quantity_editable:row.querySelector('[data-item-editable]').checked});toast('Item atualizado.','success')}catch(err){toast(err.message,'error')}}

// Captura antes do app base para substituir o modal somente no produto.
document.addEventListener('click',e=>{const p=e.target.closest('[data-open-product]');if(p){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openEditableProduct(p.dataset.openProduct);return}const b=e.target.closest('[data-open-basket]');if(b){openBasket(b.dataset.openBasket);return}if(e.target.closest('[data-enh-close]'))closeModal();const nav=e.target.closest('[data-route="baskets"]');if(nav)setTimeout(()=>{$('pageTitle').textContent='Cestas básicas';$('pageSubtitle').textContent='Preço comercial, composição e regras de personalização.';loadBaskets()},0)},true);
$('newBasketButton')?.addEventListener('click',renderNewBasket);$('basketSearch')?.addEventListener('input',()=>{clearTimeout(basketTimer);basketTimer=setTimeout(loadBaskets,220)});
})();
