import { loadCatalog, createProductIndex } from '../shared/catalog.js';
import { loadHomeCollections } from '../shared/collections.js';
import { auditKits, filterKitAudits } from './kit-audit.js';

const content=document.getElementById('admin-content');
const status=document.getElementById('admin-status');
const title=document.getElementById('module-title');
const subtitle=document.getElementById('module-subtitle');
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const metric=(value,label)=>`<article class="metric"><strong>${value}</strong><span>${label}</span></article>`;
const moduleState={loaded:false,loading:false,kits:[],productIndex:new Map(),query:'',filter:'',selectedId:''};

function periodLabel(value){return value==='expired'?'Encerrado':value==='scheduled'?'Agendado':'Ativo';}
function carouselLabel(audit){if(!audit.carouselGenerated)return 'Não gerado';return audit.carouselStatus?`Gerado · ${audit.carouselStatus}`:'Gerado';}
function issues(audit){return [
  ...audit.missing.map(ref=>`Produto não encontrado: ${ref}`),
  ...audit.unavailable.map(ref=>`Produto indisponível ou sem preço: ${ref}`),
  ...audit.insufficient.map(item=>`Estoque insuficiente: ${item.ref} (${item.stock}/${item.required})`),
  ...(!audit.periodValid?['Período inválido: a data final é anterior à inicial.']:[]),
  ...(audit.commercialPrice<=0?['Preço promocional não informado.']:[]),
  ...(audit.retailTotal<=0?['Não foi possível calcular a soma avulsa.']:[])
];}

function kitRow(audit){return `<button class="kit-audit-row" type="button" data-kit-detail="${escapeHtml(audit.kit.id)}"><span><strong>${escapeHtml(audit.kit.nome)}</strong><small>${audit.rows.length} itens · ${periodLabel(audit.periodStatus)}</small></span><span class="score ${audit.valid?'ok':'warn'}">${audit.valid?'Válido':'Bloqueado'}</span><span>${money(audit.commercialPrice)}</span><span>${audit.discount}%</span><span class="carousel-state ${audit.carouselGenerated?'ok':'pending'}">${escapeHtml(carouselLabel(audit))}</span></button>`;}

function renderDetail(audit){const foundIssues=issues(audit);content.innerHTML=`<section class="product-detail-panel"><button class="back-button" type="button" data-close-kit-detail>← Voltar aos kits</button><div class="panel-head"><div><span class="eyebrow">PROMOÇÃO · SOMENTE LEITURA</span><h2>${escapeHtml(audit.kit.nome)}</h2></div><span class="score ${audit.valid?'ok':'warn'}">${audit.valid?'Kit válido':'Kit bloqueado'}</span></div><section class="metrics">${metric(audit.rows.length,'ITENS RESOLVIDOS')}${metric(audit.periodStatus==='active'?'Ativo':periodLabel(audit.periodStatus).toUpperCase(),'PERÍODO')}${metric(money(audit.savings),'ECONOMIA')}${metric(audit.discount+'%','DESCONTO')}</section><div class="kit-commercial-grid"><article><span>Preço promocional</span><strong>${money(audit.commercialPrice)}</strong></article><article><span>Soma avulsa atual</span><strong>${money(audit.retailTotal)}</strong></article><article><span>Economia</span><strong>${money(audit.savings)}</strong></article><article><span>Carrossel Instagram</span><strong>${escapeHtml(carouselLabel(audit))}</strong></article><article><span>Início</span><strong>${escapeHtml(audit.kit.inicio||'Não informado')}</strong></article><article><span>Fim</span><strong>${escapeHtml(audit.kit.fim||'Não informado')}</strong></article></div><div class="basket-items-table"><div class="basket-items-head"><span>Produto</span><span>Qtd.</span><span>Estoque</span><span>Unitário</span><span>Subtotal</span></div>${audit.rows.map(row=>`<div><span><strong>${escapeHtml(row.product.nome)}</strong><small>${escapeHtml(row.product.codigo||row.product.id)}</small></span><span>${row.quantity}</span><span class="${row.stock<row.quantity?'text-error':''}">${row.stock}</span><span>${money(row.unitPrice)}</span><span>${money(row.subtotal)}</span></div>`).join('')||'<div class="empty">Nenhum produto válido.</div>'}</div>${foundIssues.length?`<div class="notice error"><strong>Problemas encontrados</strong><br>${foundIssues.map(escapeHtml).join('<br>')}</div>`:'<div class="notice success">Composição, preço e período estão coerentes com o catálogo atual.</div>'}<div class="notice">A geração do carrossel, inclusão em fila, uso de IA e publicação permanecem fora deste módulo de auditoria.</div></section>`;}

function render(){title.textContent='Kits promocionais';subtitle.textContent='Composição, período, desconto e carrossel separados das ações de geração e publicação.';const audit=auditKits(moduleState.kits,moduleState.productIndex);if(moduleState.selectedId){const selected=audit.rows.find(row=>String(row.kit.id)===moduleState.selectedId);if(selected){renderDetail(selected);return;}moduleState.selectedId='';}const filtered=filterKitAudits(audit.rows,moduleState.query,moduleState.filter);content.innerHTML=`<section class="module-hero"><span class="eyebrow">PROMOÇÕES · SOMENTE LEITURA</span><h2>Auditoria dos kits promocionais</h2><p>Produtos, estoque, preço, período da promoção e situação do carrossel são avaliados separadamente.</p></section><section class="metrics">${metric(audit.total,'KITS')}${metric(audit.valid,'VÁLIDOS')}${metric(audit.expired,'ENCERRADOS')}${metric(audit.carouselGenerated,'COM CARROSSEL')}</section><section class="panel"><div class="product-filters kit-filters"><label><span>Buscar kit</span><input id="kit-query" value="${escapeHtml(moduleState.query)}" placeholder="Nome ou código"></label><label><span>Filtro</span><select id="kit-filter"><option value="">Todos</option><option value="valid"${moduleState.filter==='valid'?' selected':''}>Válidos</option><option value="blocked"${moduleState.filter==='blocked'?' selected':''}>Bloqueados</option><option value="active"${moduleState.filter==='active'?' selected':''}>Promoção ativa</option><option value="expired"${moduleState.filter==='expired'?' selected':''}>Encerrados</option><option value="carousel"${moduleState.filter==='carousel'?' selected':''}>Com carrossel</option><option value="no-carousel"${moduleState.filter==='no-carousel'?' selected':''}>Sem carrossel</option></select></label></div><div class="kit-audit-head"><span>Kit</span><span>Status</span><span>Preço</span><span>Desconto</span><span>Carrossel</span></div><div class="kit-audit-list">${filtered.map(kitRow).join('')||'<div class="empty">Nenhum kit encontrado.</div>'}</div></section>`;document.getElementById('kit-query')?.addEventListener('input',event=>{moduleState.query=event.target.value;render();document.getElementById('kit-query')?.focus();});document.getElementById('kit-filter')?.addEventListener('change',event=>{moduleState.filter=event.target.value;render();});}

async function openModule(){document.querySelectorAll('[data-module]').forEach(button=>button.classList.toggle('active',button.dataset.module==='kits'));if(moduleState.loaded){render();return;}if(moduleState.loading)return;moduleState.loading=true;title.textContent='Kits promocionais';subtitle.textContent='Carregando auditoria independente…';content.innerHTML='<div class="panel"><div class="empty">Carregando kits e catálogo seguro…</div></div>';try{const [catalog,collections]=await Promise.all([loadCatalog(),loadHomeCollections()]);moduleState.productIndex=createProductIndex(catalog.products);moduleState.kits=collections.kits;moduleState.loaded=true;status.textContent=`${collections.kits.length} kits auditados`;status.dataset.type='success';render();}catch(error){status.textContent='Falha ao auditar kits';status.dataset.type='error';content.innerHTML=`<div class="panel"><div class="notice error">${escapeHtml(error.message||error)}</div></div>`;}finally{moduleState.loading=false;}}

document.addEventListener('click',event=>{const kitButton=event.target.closest('[data-module="kits"]');if(kitButton){event.preventDefault();event.stopImmediatePropagation();openModule();return;}const detail=event.target.closest('[data-kit-detail]');if(detail){moduleState.selectedId=detail.dataset.kitDetail;render();return;}if(event.target.closest('[data-close-kit-detail]')){moduleState.selectedId='';render();}},true);
