(()=>{
const cfg=window.DA_FULFILLMENT_CONFIG||{};const $=s=>document.querySelector(s);const state={sb:null,session:null,staff:null,runtime:null,queue:[],current:null,tab:'queue'};const qkey='da_fulfillment_queue_v1';
const eventId=p=>`${p}:${crypto.randomUUID()}`;const toast=(m,bad=false)=>{const e=$('#toast');e.textContent=m;e.className=bad?'bad':'ok';clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='',2600)};
const api=async body=>{if(!state.session?.access_token)throw new Error('auth_required');const r=await fetch(cfg.apiBase,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${state.session.access_token}`},body:JSON.stringify(body)});const j=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||j.ok===false)throw Object.assign(new Error(j.error||'request_failed'),{payload:j});return j};
const queueLocal=()=>JSON.parse(localStorage.getItem(qkey)||'[]');const saveLocal=x=>localStorage.setItem(qkey,JSON.stringify(x));const enqueue=x=>{const a=queueLocal();a.push(x);saveLocal(a)};
async function flush(){if(!navigator.onLine)return;const a=queueLocal(),left=[];for(const x of a){try{await api(x)}catch{left.push(x)}}saveLocal(left)}
function showGate(msg){$('#gate').textContent=msg;$('#gate').classList.remove('hidden');$('#me').classList.add('hidden');$('#tabs').classList.add('hidden')}
function renderMe(){const s=state.staff;$('#gate').classList.add('hidden');$('#me').classList.remove('hidden');$('#tabs').classList.remove('hidden');$('#me').innerHTML=`<b>${escapeHtml(s.display_name)}</b><span>${escapeHtml(s.role)} · ${navigator.onLine?'online':'offline'}</span>`;}
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function setTab(t){state.tab=t;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$('#queueView').classList.toggle('hidden',t!=='queue');$('#workView').classList.toggle('hidden',t!=='work')}
function renderQueue(){const q=$('#queue');q.innerHTML=state.queue.length?state.queue.map(x=>`<button class="orderCard" data-id="${x.id}"><b>Pedido ${escapeHtml(x.order_id.slice(0,8))}</b><span>${escapeHtml(x.status)}</span></button>`).join(''):'<div class="card">Nenhum pedido disponível.</div>';q.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openOrder(b.dataset.id));}
function currentPhase(){const s=state.current?.order?.status;if(['pending','picking'].includes(s))return'picking';if(['picked','checking'].includes(s))return'checking';return null}
function renderCurrent(){const snap=state.current;if(!snap)return;const fo=snap.order||{};$('#orderHeader').innerHTML=`<b>Pedido ${escapeHtml(String(fo.order_id||'').slice(0,8))}</b><span>Status: ${escapeHtml(fo.status)}</span>`;const tasks=snap.tasks||[];const phase=currentPhase();const next=tasks.find(t=>phase==='checking'?Number(t.checked_quantity)<Number(t.required_quantity):Number(t.picked_quantity)<Number(t.required_quantity));$('#nextTask').innerHTML=next?`<small>PRÓXIMO ITEM</small><h2>${escapeHtml(next.name_snapshot)}</h2><p>${escapeHtml(next.location_snapshot?.gondola||'—')} · ${escapeHtml(next.location_snapshot?.shelf||'—')}</p><strong>${phase==='checking'?next.checked_quantity:next.picked_quantity}/${next.required_quantity}</strong><code>${escapeHtml(next.gtin_snapshot||next.sku_snapshot||'SEM CÓDIGO')}</code>`:'<b>Etapa sem itens pendentes.</b>';$('#tasks').innerHTML=tasks.map(t=>`<div class="task"><div><b>${escapeHtml(t.name_snapshot)}</b><span>${escapeHtml(t.location_snapshot?.code||'sem posição')}</span></div><strong>${phase==='checking'?t.checked_quantity:t.picked_quantity}/${t.required_quantity}</strong></div>`).join('');const ex=snap.open_exceptions||[];$('#exceptions').innerHTML=ex.length?`<div class="card badbox"><b>Exceções abertas: ${ex.length}</b></div>`:'';$('#scanForm').classList.toggle('hidden',!phase);$('#startBtn').classList.toggle('hidden',fo.status!=='pending'||!state.staff?.can_pick);$('#completeBtn').classList.toggle('hidden',!phase);$('#completeBtn').textContent=phase==='checking'?'Concluir conferência':'Concluir separação';setTimeout(()=>$('#barcode')?.focus(),50)}
async function loadQueue(){const j=await api({action:'queue'});state.queue=j.items||[];renderQueue()}
async function openOrder(id){const j=await api({action:'snapshot',fulfillment_order_id:id});state.current=j.snapshot;setTab('work');renderCurrent()}
async function refreshCurrent(){if(state.current?.order?.id)await openOrder(state.current.order.id)}
async function init(){if(!cfg.enabled)return showGate('Fulfillment mobile está desligado.');if(!cfg.supabaseUrl||!cfg.supabasePublishableKey)return showGate('Configuração de autenticação ainda não publicada.');state.sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const{data}=await state.sb.auth.getSession();state.session=data.session;if(!state.session)return showGate('Faça login no portal operacional antes de usar este aplicativo.');try{const me=await api({action:'me'});state.staff=me.staff;state.runtime=me.runtime;if(!state.runtime?.enabled)return showGate('Fulfillment está em modo OFF.');renderMe();setTab('queue');await flush();await loadQueue()}catch(e){showGate(e.message==='staff_not_active'?'Funcionário não habilitado para operações.':`Acesso indisponível: ${e.message}`)}}
$('#refreshBtn').onclick=async()=>{try{await flush();if(state.tab==='queue')await loadQueue();else await refreshCurrent();toast('Atualizado')}catch(e){toast(e.message,true)}};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('#startBtn').onclick=async()=>{try{await api({action:'start_picking',fulfillment_order_id:state.current.order.id,client_event_id:eventId('pick-start')});await refreshCurrent();toast('Separação iniciada')}catch(e){toast(e.message,true)}};
$('#scanForm').onsubmit=async ev=>{ev.preventDefault();const bc=$('#barcode').value.trim(),qty=Number($('#qty').value||1),phase=currentPhase();if(!bc||!phase)return;const body={action:'scan',fulfillment_order_id:state.current.order.id,phase,barcode:bc,quantity:qty,device_id:cfg.deviceLabel||navigator.userAgent.slice(0,80),client_event_id:eventId(`scan-${phase}`)};$('#barcode').value='';try{if(!navigator.onLine&&cfg.offlineQueueEnabled){enqueue(body);toast('Leitura guardada offline');return}await api(body);await refreshCurrent();toast('Leitura aceita')}catch(e){navigator.vibrate?.([120,60,120]);toast(e.payload?.error||e.message,true)}finally{$('#barcode').focus()}};
$('#completeBtn').onclick=async()=>{const phase=currentPhase();if(!phase)return;try{await api({action:'complete_phase',fulfillment_order_id:state.current.order.id,phase,client_event_id:eventId(`complete-${phase}`)});await refreshCurrent();toast(phase==='checking'?'Conferência concluída':'Separação concluída')}catch(e){toast(e.payload?.error||e.message,true)}};
window.addEventListener('online',()=>flush().then(()=>toast('Sincronizado')).catch(()=>{}));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});init();
})();
