const cfg=window.DA_WAREHOUSE_CONFIG||{};const $=s=>document.querySelector(s);const queueKey=cfg.offlineQueueKey||'da_warehouse_queue_v1';const state={phase:'picking',order:null,items:[]};
const qread=()=>{try{return JSON.parse(localStorage.getItem(queueKey)||'[]')}catch{return[]}};const qwrite=q=>localStorage.setItem(queueKey,JSON.stringify(q));
function setFeedback(msg,ok=false){$('#feedback').textContent=msg;$('#feedback').className=ok?'ok':'muted'}
function current(){return state.items.find(i=>(state.phase==='picking'?Number(i.picked_quantity):Number(i.checked_quantity))<Number(i.expected_quantity))||null}
function render(){const i=current();$('#phase').textContent=state.phase==='picking'?'separação':'conferência';$('#orderTitle').textContent=state.order?`Pedido ${state.order.order_id}`:'Pedido';const done=state.items.filter(x=>(state.phase==='picking'?Number(x.picked_quantity):Number(x.checked_quantity))>=Number(x.expected_quantity)).length;$('#progress').textContent=`${done}/${state.items.length}`;$('#productName').textContent=i?.name_snapshot||'Etapa concluída';$('#location').textContent=i?`${i.location_code||'SEM POSIÇÃO'} · ${i.gondola_code||''} ${i.shelf_code||''}`:'—';$('#lot').textContent=i?.lot_code?`Lote ${i.lot_code}${i.expires_on?' · validade '+i.expires_on:''}`:'';const n=i?(state.phase==='picking'?i.picked_quantity:i.checked_quantity):0;$('#qty').textContent=i?`${n} / ${i.expected_quantity}`:'✓';$('#barcode').disabled=!i;if(i)setTimeout(()=>$('#barcode').focus(),50)}
async function call(action,payload){const body={action,...payload};if(!navigator.onLine){const q=qread();q.push({id:crypto.randomUUID(),body,created_at:new Date().toISOString()});qwrite(q);return {ok:true,queued_offline:true}}throw new Error('warehouse API not deployed');}
async function onScan(){const input=$('#barcode');const code=input.value.trim();input.value='';const i=current();if(!code||!i)return;const client_event_id=`wh:${crypto.randomUUID()}`;try{const r=await call('scan',{fulfillment_order_id:state.order?.id,phase:state.phase,barcode:code,client_event_id});if(r.queued_offline){setFeedback('Leitura guardada offline. Será sincronizada quando o módulo estiver homologado.',true);const field=state.phase==='picking'?'picked_quantity':'checked_quantity';i[field]=Number(i[field])+1;render();return}setFeedback('Leitura registrada.',true)}catch(e){setFeedback(String(e.message||e))}}
$('#barcode').addEventListener('change',onScan);$('#barcode').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();onScan()}});$('#finish').addEventListener('click',()=>setFeedback('Finalização permanece bloqueada enquanto o módulo está OFF.'));
if(cfg.enabled){$('#mode').textContent='homologação';$('#app').classList.remove('hidden')}else{$('#mode').textContent='módulo WMS desligado — nenhuma operação real liberada'}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
